package com.t.zero.yg.crm.bu.dao.auto;

import com.t.zero.yg.crm.bu.model.auto.CorpAddress;
import com.t.zero.yg.crm.bu.model.auto.CorpAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CorpAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    long countByExample(CorpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int deleteByExample(CorpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int insert(CorpAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int insertSelective(CorpAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    List<CorpAddress> selectByExampleWithBLOBs(CorpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    List<CorpAddress> selectByExample(CorpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    CorpAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByExampleSelective(@Param("record") CorpAddress record, @Param("example") CorpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CorpAddress record, @Param("example") CorpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByExample(@Param("record") CorpAddress record, @Param("example") CorpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByPrimaryKeySelective(CorpAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CorpAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByPrimaryKey(CorpAddress record);
}