package com.t.zero.yg.crm.bu.dao.auto;

import com.t.zero.yg.crm.bu.model.auto.CorpContact;
import com.t.zero.yg.crm.bu.model.auto.CorpContactExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CorpContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    long countByExample(CorpContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    int deleteByExample(CorpContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    int insert(CorpContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    int insertSelective(CorpContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    List<CorpContact> selectByExampleWithBLOBs(CorpContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    List<CorpContact> selectByExample(CorpContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    CorpContact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    int updateByExampleSelective(@Param("record") CorpContact record, @Param("example") CorpContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CorpContact record, @Param("example") CorpContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    int updateByExample(@Param("record") CorpContact record, @Param("example") CorpContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    int updateByPrimaryKeySelective(CorpContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CorpContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_contact
     *
     * @mbg.generated Fri May 27 12:58:51 CST 2022
     */
    int updateByPrimaryKey(CorpContact record);
}