package com.t.zero.yg.crm.bu.dao.auto;

import com.t.zero.yg.crm.bu.model.auto.CustomerDefBuss;
import com.t.zero.yg.crm.bu.model.auto.CustomerDefBussExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerDefBussMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    long countByExample(CustomerDefBussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    int deleteByExample(CustomerDefBussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    int insert(CustomerDefBuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    int insertSelective(CustomerDefBuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    List<CustomerDefBuss> selectByExampleWithBLOBs(CustomerDefBussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    List<CustomerDefBuss> selectByExample(CustomerDefBussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    CustomerDefBuss selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    int updateByExampleSelective(@Param("record") CustomerDefBuss record, @Param("example") CustomerDefBussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CustomerDefBuss record, @Param("example") CustomerDefBussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    int updateByExample(@Param("record") CustomerDefBuss record, @Param("example") CustomerDefBussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    int updateByPrimaryKeySelective(CustomerDefBuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CustomerDefBuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_customer_def_buss
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    int updateByPrimaryKey(CustomerDefBuss record);
}