package com.t.zero.yg.crm.bu.dao.auto;

import com.t.zero.yg.crm.bu.model.auto.FieldGroupDef;
import com.t.zero.yg.crm.bu.model.auto.FieldGroupDefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FieldGroupDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    long countByExample(FieldGroupDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int deleteByExample(FieldGroupDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int insert(FieldGroupDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int insertSelective(FieldGroupDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    List<FieldGroupDef> selectByExampleWithBLOBs(FieldGroupDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    List<FieldGroupDef> selectByExample(FieldGroupDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    FieldGroupDef selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByExampleSelective(@Param("record") FieldGroupDef record, @Param("example") FieldGroupDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") FieldGroupDef record, @Param("example") FieldGroupDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByExample(@Param("record") FieldGroupDef record, @Param("example") FieldGroupDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByPrimaryKeySelective(FieldGroupDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(FieldGroupDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_field_group_def
     *
     * @mbg.generated Fri May 27 14:14:07 CST 2022
     */
    int updateByPrimaryKey(FieldGroupDef record);
}