package com.t.zero.res.c.manager.bu.model.manual;

import java.time.LocalDateTime;

import com.fasterxml.jackson.databind.JsonNode;

import lombok.Data;

@Data
public class TemplateTypeDefVo {

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_template_type_def.id
	 *
	 * @mbg.generated Tue May 17 10:44:54 CST 2022
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_template_type_def.tenant_id
	 *
	 * @mbg.generated Tue May 17 10:44:54 CST 2022
	 */
	private Integer tenantId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_template_type_def.template_type_code
	 *
	 * @mbg.generated Tue May 17 10:44:54 CST 2022
	 */
	private String templateTypeCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_template_type_def.template_type_name
	 *
	 * @mbg.generated Tue May 17 10:44:54 CST 2022
	 */
	private String templateTypeName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_template_type_def.created_user_id
	 *
	 * @mbg.generated Tue May 17 10:44:54 CST 2022
	 */
	private String createdUserId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_template_type_def.created_time
	 *
	 * @mbg.generated Tue May 17 10:44:54 CST 2022
	 */
	private LocalDateTime createdTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_template_type_def.updated_user_id
	 *
	 * @mbg.generated Tue May 17 10:44:54 CST 2022
	 */
	private String updatedUserId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_template_type_def.updated_time
	 *
	 * @mbg.generated Tue May 17 10:44:54 CST 2022
	 */
	private LocalDateTime updatedTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_template_type_def.is_deleted
	 *
	 * @mbg.generated Tue May 17 10:44:54 CST 2022
	 */
	private String deletedFlag;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_template_type_def.template_type_desc
	 *
	 * @mbg.generated Tue May 17 10:44:54 CST 2022
	 */
	private JsonNode templateTypeDesc;

}
