package com.t.zero.res.c.manager.bu.dao.auto;

import com.t.zero.res.c.manager.bu.model.auto.ResInfoDef;
import com.t.zero.res.c.manager.bu.model.auto.ResInfoDefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResInfoDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    long countByExample(ResInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    int deleteByExample(ResInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    int insert(ResInfoDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    int insertSelective(ResInfoDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    List<ResInfoDef> selectByExample(ResInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    ResInfoDef selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    int updateByExampleSelective(@Param("record") ResInfoDef record, @Param("example") ResInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    int updateByExample(@Param("record") ResInfoDef record, @Param("example") ResInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    int updateByPrimaryKeySelective(ResInfoDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    int updateByPrimaryKey(ResInfoDef record);
}