package com.t.zero.res.c.manager.bu.dao.auto;

import com.t.zero.res.c.manager.bu.model.auto.ResTagRel;
import com.t.zero.res.c.manager.bu.model.auto.ResTagRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResTagRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    long countByExample(ResTagRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int deleteByExample(ResTagRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int insert(ResTagRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int insertSelective(ResTagRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    List<ResTagRel> selectByExample(ResTagRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    ResTagRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByExampleSelective(@Param("record") ResTagRel record, @Param("example") ResTagRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByExample(@Param("record") ResTagRel record, @Param("example") ResTagRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByPrimaryKeySelective(ResTagRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByPrimaryKey(ResTagRel record);
}