package com.t.zero.res.c.manager.bu.dao.auto;

import com.t.zero.res.c.manager.bu.model.auto.ResTaskDef;
import com.t.zero.res.c.manager.bu.model.auto.ResTaskDefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResTaskDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_task_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    long countByExample(ResTaskDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_task_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int deleteByExample(ResTaskDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_task_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_task_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int insert(ResTaskDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_task_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int insertSelective(ResTaskDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_task_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    List<ResTaskDef> selectByExample(ResTaskDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_task_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    ResTaskDef selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_task_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByExampleSelective(@Param("record") ResTaskDef record, @Param("example") ResTaskDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_task_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByExample(@Param("record") ResTaskDef record, @Param("example") ResTaskDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_task_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByPrimaryKeySelective(ResTaskDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_task_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByPrimaryKey(ResTaskDef record);
}