package com.t.zero.res.c.manager.bu.dao.auto;

import com.t.zero.res.c.manager.bu.model.auto.ResTagDef;
import com.t.zero.res.c.manager.bu.model.auto.ResTagDefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResTagDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    long countByExample(ResTagDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int deleteByExample(ResTagDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int insert(ResTagDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int insertSelective(ResTagDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    List<ResTagDef> selectByExample(ResTagDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    ResTagDef selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByExampleSelective(@Param("record") ResTagDef record, @Param("example") ResTagDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByExample(@Param("record") ResTagDef record, @Param("example") ResTagDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByPrimaryKeySelective(ResTagDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_def
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    int updateByPrimaryKey(ResTagDef record);
}