package com.t.zero.res.c.manager.bu.dao.auto;

import com.t.zero.res.c.manager.bu.model.auto.TemplateTypeDef;
import com.t.zero.res.c.manager.bu.model.auto.TemplateTypeDefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TemplateTypeDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    long countByExample(TemplateTypeDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int deleteByExample(TemplateTypeDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int insert(TemplateTypeDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int insertSelective(TemplateTypeDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    List<TemplateTypeDef> selectByExampleWithBLOBs(TemplateTypeDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    List<TemplateTypeDef> selectByExample(TemplateTypeDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    TemplateTypeDef selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByExampleSelective(@Param("record") TemplateTypeDef record, @Param("example") TemplateTypeDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") TemplateTypeDef record, @Param("example") TemplateTypeDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByExample(@Param("record") TemplateTypeDef record, @Param("example") TemplateTypeDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByPrimaryKeySelective(TemplateTypeDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(TemplateTypeDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_type_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByPrimaryKey(TemplateTypeDef record);
}