package com.t.zero.res.c.manager.bu.dao.auto;

import com.t.zero.res.c.manager.bu.model.auto.TemplateInfoDef;
import com.t.zero.res.c.manager.bu.model.auto.TemplateInfoDefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TemplateInfoDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    long countByExample(TemplateInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int deleteByExample(TemplateInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int insert(TemplateInfoDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int insertSelective(TemplateInfoDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    List<TemplateInfoDef> selectByExampleWithBLOBs(TemplateInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    List<TemplateInfoDef> selectByExample(TemplateInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    TemplateInfoDef selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByExampleSelective(@Param("record") TemplateInfoDef record, @Param("example") TemplateInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") TemplateInfoDef record, @Param("example") TemplateInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByExample(@Param("record") TemplateInfoDef record, @Param("example") TemplateInfoDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByPrimaryKeySelective(TemplateInfoDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(TemplateInfoDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    int updateByPrimaryKey(TemplateInfoDef record);
}