package com.t.zero.yg.crm.bu.model.auto;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class CorpInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public CorpInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPvCodeIsNull() {
            addCriterion("pv_code is null");
            return (Criteria) this;
        }

        public Criteria andPvCodeIsNotNull() {
            addCriterion("pv_code is not null");
            return (Criteria) this;
        }

        public Criteria andPvCodeEqualTo(String value) {
            addCriterion("pv_code =", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeNotEqualTo(String value) {
            addCriterion("pv_code <>", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeGreaterThan(String value) {
            addCriterion("pv_code >", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeGreaterThanOrEqualTo(String value) {
            addCriterion("pv_code >=", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeLessThan(String value) {
            addCriterion("pv_code <", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeLessThanOrEqualTo(String value) {
            addCriterion("pv_code <=", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeLike(String value) {
            addCriterion("pv_code like", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeNotLike(String value) {
            addCriterion("pv_code not like", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeIn(List<String> values) {
            addCriterion("pv_code in", values, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeNotIn(List<String> values) {
            addCriterion("pv_code not in", values, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeBetween(String value1, String value2) {
            addCriterion("pv_code between", value1, value2, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeNotBetween(String value1, String value2) {
            addCriterion("pv_code not between", value1, value2, "pvCode");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(Integer value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(Integer value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(Integer value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(Integer value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(Integer value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<Integer> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<Integer> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(Integer value1, Integer value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andCorpBriefIsNull() {
            addCriterion("corp_brief is null");
            return (Criteria) this;
        }

        public Criteria andCorpBriefIsNotNull() {
            addCriterion("corp_brief is not null");
            return (Criteria) this;
        }

        public Criteria andCorpBriefEqualTo(String value) {
            addCriterion("corp_brief =", value, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpBriefNotEqualTo(String value) {
            addCriterion("corp_brief <>", value, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpBriefGreaterThan(String value) {
            addCriterion("corp_brief >", value, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpBriefGreaterThanOrEqualTo(String value) {
            addCriterion("corp_brief >=", value, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpBriefLessThan(String value) {
            addCriterion("corp_brief <", value, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpBriefLessThanOrEqualTo(String value) {
            addCriterion("corp_brief <=", value, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpBriefLike(String value) {
            addCriterion("corp_brief like", value, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpBriefNotLike(String value) {
            addCriterion("corp_brief not like", value, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpBriefIn(List<String> values) {
            addCriterion("corp_brief in", values, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpBriefNotIn(List<String> values) {
            addCriterion("corp_brief not in", values, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpBriefBetween(String value1, String value2) {
            addCriterion("corp_brief between", value1, value2, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpBriefNotBetween(String value1, String value2) {
            addCriterion("corp_brief not between", value1, value2, "corpBrief");
            return (Criteria) this;
        }

        public Criteria andCorpNameIsNull() {
            addCriterion("corp_name is null");
            return (Criteria) this;
        }

        public Criteria andCorpNameIsNotNull() {
            addCriterion("corp_name is not null");
            return (Criteria) this;
        }

        public Criteria andCorpNameEqualTo(String value) {
            addCriterion("corp_name =", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotEqualTo(String value) {
            addCriterion("corp_name <>", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameGreaterThan(String value) {
            addCriterion("corp_name >", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameGreaterThanOrEqualTo(String value) {
            addCriterion("corp_name >=", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameLessThan(String value) {
            addCriterion("corp_name <", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameLessThanOrEqualTo(String value) {
            addCriterion("corp_name <=", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameLike(String value) {
            addCriterion("corp_name like", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotLike(String value) {
            addCriterion("corp_name not like", value, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameIn(List<String> values) {
            addCriterion("corp_name in", values, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotIn(List<String> values) {
            addCriterion("corp_name not in", values, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameBetween(String value1, String value2) {
            addCriterion("corp_name between", value1, value2, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpNameNotBetween(String value1, String value2) {
            addCriterion("corp_name not between", value1, value2, "corpName");
            return (Criteria) this;
        }

        public Criteria andCorpTypeIsNull() {
            addCriterion("corp_type is null");
            return (Criteria) this;
        }

        public Criteria andCorpTypeIsNotNull() {
            addCriterion("corp_type is not null");
            return (Criteria) this;
        }

        public Criteria andCorpTypeEqualTo(String value) {
            addCriterion("corp_type =", value, "corpType");
            return (Criteria) this;
        }

        public Criteria andCorpTypeNotEqualTo(String value) {
            addCriterion("corp_type <>", value, "corpType");
            return (Criteria) this;
        }

        public Criteria andCorpTypeGreaterThan(String value) {
            addCriterion("corp_type >", value, "corpType");
            return (Criteria) this;
        }

        public Criteria andCorpTypeGreaterThanOrEqualTo(String value) {
            addCriterion("corp_type >=", value, "corpType");
            return (Criteria) this;
        }

        public Criteria andCorpTypeLessThan(String value) {
            addCriterion("corp_type <", value, "corpType");
            return (Criteria) this;
        }

        public Criteria andCorpTypeLessThanOrEqualTo(String value) {
            addCriterion("corp_type <=", value, "corpType");
            return (Criteria) this;
        }

        public Criteria andCorpTypeLike(String value) {
            addCriterion("corp_type like", value, "corpType");
            return (Criteria) this;
        }

        public Criteria andCorpTypeNotLike(String value) {
            addCriterion("corp_type not like", value, "corpType");
            return (Criteria) this;
        }

        public Criteria andCorpTypeIn(List<String> values) {
            addCriterion("corp_type in", values, "corpType");
            return (Criteria) this;
        }

        public Criteria andCorpTypeNotIn(List<String> values) {
            addCriterion("corp_type not in", values, "corpType");
            return (Criteria) this;
        }

        public Criteria andCorpTypeBetween(String value1, String value2) {
            addCriterion("corp_type between", value1, value2, "corpType");
            return (Criteria) this;
        }

        public Criteria andCorpTypeNotBetween(String value1, String value2) {
            addCriterion("corp_type not between", value1, value2, "corpType");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeIsNull() {
            addCriterion("industry_code is null");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeIsNotNull() {
            addCriterion("industry_code is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeEqualTo(String value) {
            addCriterion("industry_code =", value, "industryCode");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeNotEqualTo(String value) {
            addCriterion("industry_code <>", value, "industryCode");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeGreaterThan(String value) {
            addCriterion("industry_code >", value, "industryCode");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("industry_code >=", value, "industryCode");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeLessThan(String value) {
            addCriterion("industry_code <", value, "industryCode");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeLessThanOrEqualTo(String value) {
            addCriterion("industry_code <=", value, "industryCode");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeLike(String value) {
            addCriterion("industry_code like", value, "industryCode");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeNotLike(String value) {
            addCriterion("industry_code not like", value, "industryCode");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeIn(List<String> values) {
            addCriterion("industry_code in", values, "industryCode");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeNotIn(List<String> values) {
            addCriterion("industry_code not in", values, "industryCode");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeBetween(String value1, String value2) {
            addCriterion("industry_code between", value1, value2, "industryCode");
            return (Criteria) this;
        }

        public Criteria andIndustryCodeNotBetween(String value1, String value2) {
            addCriterion("industry_code not between", value1, value2, "industryCode");
            return (Criteria) this;
        }

        public Criteria andPvStatusIsNull() {
            addCriterion("pv_status is null");
            return (Criteria) this;
        }

        public Criteria andPvStatusIsNotNull() {
            addCriterion("pv_status is not null");
            return (Criteria) this;
        }

        public Criteria andPvStatusEqualTo(String value) {
            addCriterion("pv_status =", value, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andPvStatusNotEqualTo(String value) {
            addCriterion("pv_status <>", value, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andPvStatusGreaterThan(String value) {
            addCriterion("pv_status >", value, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andPvStatusGreaterThanOrEqualTo(String value) {
            addCriterion("pv_status >=", value, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andPvStatusLessThan(String value) {
            addCriterion("pv_status <", value, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andPvStatusLessThanOrEqualTo(String value) {
            addCriterion("pv_status <=", value, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andPvStatusLike(String value) {
            addCriterion("pv_status like", value, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andPvStatusNotLike(String value) {
            addCriterion("pv_status not like", value, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andPvStatusIn(List<String> values) {
            addCriterion("pv_status in", values, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andPvStatusNotIn(List<String> values) {
            addCriterion("pv_status not in", values, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andPvStatusBetween(String value1, String value2) {
            addCriterion("pv_status between", value1, value2, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andPvStatusNotBetween(String value1, String value2) {
            addCriterion("pv_status not between", value1, value2, "pvStatus");
            return (Criteria) this;
        }

        public Criteria andCorpLevelIsNull() {
            addCriterion("corp_level is null");
            return (Criteria) this;
        }

        public Criteria andCorpLevelIsNotNull() {
            addCriterion("corp_level is not null");
            return (Criteria) this;
        }

        public Criteria andCorpLevelEqualTo(Integer value) {
            addCriterion("corp_level =", value, "corpLevel");
            return (Criteria) this;
        }

        public Criteria andCorpLevelNotEqualTo(Integer value) {
            addCriterion("corp_level <>", value, "corpLevel");
            return (Criteria) this;
        }

        public Criteria andCorpLevelGreaterThan(Integer value) {
            addCriterion("corp_level >", value, "corpLevel");
            return (Criteria) this;
        }

        public Criteria andCorpLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("corp_level >=", value, "corpLevel");
            return (Criteria) this;
        }

        public Criteria andCorpLevelLessThan(Integer value) {
            addCriterion("corp_level <", value, "corpLevel");
            return (Criteria) this;
        }

        public Criteria andCorpLevelLessThanOrEqualTo(Integer value) {
            addCriterion("corp_level <=", value, "corpLevel");
            return (Criteria) this;
        }

        public Criteria andCorpLevelIn(List<Integer> values) {
            addCriterion("corp_level in", values, "corpLevel");
            return (Criteria) this;
        }

        public Criteria andCorpLevelNotIn(List<Integer> values) {
            addCriterion("corp_level not in", values, "corpLevel");
            return (Criteria) this;
        }

        public Criteria andCorpLevelBetween(Integer value1, Integer value2) {
            addCriterion("corp_level between", value1, value2, "corpLevel");
            return (Criteria) this;
        }

        public Criteria andCorpLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("corp_level not between", value1, value2, "corpLevel");
            return (Criteria) this;
        }

        public Criteria andCorpSourceIsNull() {
            addCriterion("corp_source is null");
            return (Criteria) this;
        }

        public Criteria andCorpSourceIsNotNull() {
            addCriterion("corp_source is not null");
            return (Criteria) this;
        }

        public Criteria andCorpSourceEqualTo(String value) {
            addCriterion("corp_source =", value, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCorpSourceNotEqualTo(String value) {
            addCriterion("corp_source <>", value, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCorpSourceGreaterThan(String value) {
            addCriterion("corp_source >", value, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCorpSourceGreaterThanOrEqualTo(String value) {
            addCriterion("corp_source >=", value, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCorpSourceLessThan(String value) {
            addCriterion("corp_source <", value, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCorpSourceLessThanOrEqualTo(String value) {
            addCriterion("corp_source <=", value, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCorpSourceLike(String value) {
            addCriterion("corp_source like", value, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCorpSourceNotLike(String value) {
            addCriterion("corp_source not like", value, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCorpSourceIn(List<String> values) {
            addCriterion("corp_source in", values, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCorpSourceNotIn(List<String> values) {
            addCriterion("corp_source not in", values, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCorpSourceBetween(String value1, String value2) {
            addCriterion("corp_source between", value1, value2, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCorpSourceNotBetween(String value1, String value2) {
            addCriterion("corp_source not between", value1, value2, "corpSource");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIsNull() {
            addCriterion("created_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIsNotNull() {
            addCriterion("created_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdEqualTo(String value) {
            addCriterion("created_user_id =", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotEqualTo(String value) {
            addCriterion("created_user_id <>", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdGreaterThan(String value) {
            addCriterion("created_user_id >", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("created_user_id >=", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLessThan(String value) {
            addCriterion("created_user_id <", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLessThanOrEqualTo(String value) {
            addCriterion("created_user_id <=", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLike(String value) {
            addCriterion("created_user_id like", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotLike(String value) {
            addCriterion("created_user_id not like", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIn(List<String> values) {
            addCriterion("created_user_id in", values, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotIn(List<String> values) {
            addCriterion("created_user_id not in", values, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdBetween(String value1, String value2) {
            addCriterion("created_user_id between", value1, value2, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotBetween(String value1, String value2) {
            addCriterion("created_user_id not between", value1, value2, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(LocalDateTime value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(LocalDateTime value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(LocalDateTime value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(LocalDateTime value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<LocalDateTime> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<LocalDateTime> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdIsNull() {
            addCriterion("updated_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdIsNotNull() {
            addCriterion("updated_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdEqualTo(String value) {
            addCriterion("updated_user_id =", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotEqualTo(String value) {
            addCriterion("updated_user_id <>", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdGreaterThan(String value) {
            addCriterion("updated_user_id >", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("updated_user_id >=", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdLessThan(String value) {
            addCriterion("updated_user_id <", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdLessThanOrEqualTo(String value) {
            addCriterion("updated_user_id <=", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdLike(String value) {
            addCriterion("updated_user_id like", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotLike(String value) {
            addCriterion("updated_user_id not like", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdIn(List<String> values) {
            addCriterion("updated_user_id in", values, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotIn(List<String> values) {
            addCriterion("updated_user_id not in", values, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdBetween(String value1, String value2) {
            addCriterion("updated_user_id between", value1, value2, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotBetween(String value1, String value2) {
            addCriterion("updated_user_id not between", value1, value2, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(LocalDateTime value) {
            addCriterion("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(LocalDateTime value) {
            addCriterion("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(LocalDateTime value) {
            addCriterion("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(LocalDateTime value) {
            addCriterion("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<LocalDateTime> values) {
            addCriterion("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<LocalDateTime> values) {
            addCriterion("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagEqualTo(String value) {
            addCriterion("is_deleted =", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThan(String value) {
            addCriterion("is_deleted >", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThan(String value) {
            addCriterion("is_deleted <", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLike(String value) {
            addCriterion("is_deleted like", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotLike(String value) {
            addCriterion("is_deleted not like", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIn(List<String> values) {
            addCriterion("is_deleted in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yg_corp_info
     *
     * @mbg.generated do_not_delete_during_merge Mon May 30 09:12:20 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}