package com.t.zero.yg.crm.bu.model.auto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class CorpAddress implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.pv_code
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String pvCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.tenant_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.corp_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private Integer corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.corp_code
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String corpCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.address_type
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String addressType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.country
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.postal_code
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.address_name
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String addressName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.contactor
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String contactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.telephone
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.pv_status
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String pvStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.created_user_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.created_time
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.updated_user_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.updated_time
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private LocalDateTime updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.is_deleted
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String deletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_address.pv_desc
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private String pvDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yg_corp_address
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.id
     *
     * @return the value of yg_corp_address.id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.id
     *
     * @param id the value for yg_corp_address.id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.pv_code
     *
     * @return the value of yg_corp_address.pv_code
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getPvCode() {
        return pvCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.pv_code
     *
     * @param pvCode the value for yg_corp_address.pv_code
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setPvCode(String pvCode) {
        this.pvCode = pvCode == null ? null : pvCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.tenant_id
     *
     * @return the value of yg_corp_address.tenant_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.tenant_id
     *
     * @param tenantId the value for yg_corp_address.tenant_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.corp_id
     *
     * @return the value of yg_corp_address.corp_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public Integer getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.corp_id
     *
     * @param corpId the value for yg_corp_address.corp_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setCorpId(Integer corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.corp_code
     *
     * @return the value of yg_corp_address.corp_code
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getCorpCode() {
        return corpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.corp_code
     *
     * @param corpCode the value for yg_corp_address.corp_code
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setCorpCode(String corpCode) {
        this.corpCode = corpCode == null ? null : corpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.address_type
     *
     * @return the value of yg_corp_address.address_type
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.address_type
     *
     * @param addressType the value for yg_corp_address.address_type
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setAddressType(String addressType) {
        this.addressType = addressType == null ? null : addressType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.country
     *
     * @return the value of yg_corp_address.country
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.country
     *
     * @param country the value for yg_corp_address.country
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.postal_code
     *
     * @return the value of yg_corp_address.postal_code
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.postal_code
     *
     * @param postalCode the value for yg_corp_address.postal_code
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.address_name
     *
     * @return the value of yg_corp_address.address_name
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.address_name
     *
     * @param addressName the value for yg_corp_address.address_name
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setAddressName(String addressName) {
        this.addressName = addressName == null ? null : addressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.contactor
     *
     * @return the value of yg_corp_address.contactor
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getContactor() {
        return contactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.contactor
     *
     * @param contactor the value for yg_corp_address.contactor
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setContactor(String contactor) {
        this.contactor = contactor == null ? null : contactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.telephone
     *
     * @return the value of yg_corp_address.telephone
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.telephone
     *
     * @param telephone the value for yg_corp_address.telephone
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.pv_status
     *
     * @return the value of yg_corp_address.pv_status
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getPvStatus() {
        return pvStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.pv_status
     *
     * @param pvStatus the value for yg_corp_address.pv_status
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setPvStatus(String pvStatus) {
        this.pvStatus = pvStatus == null ? null : pvStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.created_user_id
     *
     * @return the value of yg_corp_address.created_user_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.created_user_id
     *
     * @param createdUserId the value for yg_corp_address.created_user_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.created_time
     *
     * @return the value of yg_corp_address.created_time
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.created_time
     *
     * @param createdTime the value for yg_corp_address.created_time
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.updated_user_id
     *
     * @return the value of yg_corp_address.updated_user_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.updated_user_id
     *
     * @param updatedUserId the value for yg_corp_address.updated_user_id
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId == null ? null : updatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.updated_time
     *
     * @return the value of yg_corp_address.updated_time
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.updated_time
     *
     * @param updatedTime the value for yg_corp_address.updated_time
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.is_deleted
     *
     * @return the value of yg_corp_address.is_deleted
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.is_deleted
     *
     * @param deletedFlag the value for yg_corp_address.is_deleted
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_address.pv_desc
     *
     * @return the value of yg_corp_address.pv_desc
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public String getPvDesc() {
        return pvDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_address.pv_desc
     *
     * @param pvDesc the value for yg_corp_address.pv_desc
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    public void setPvDesc(String pvDesc) {
        this.pvDesc = pvDesc == null ? null : pvDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_address
     *
     * @mbg.generated Sun Jun 05 16:40:02 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pvCode=").append(pvCode);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", corpId=").append(corpId);
        sb.append(", corpCode=").append(corpCode);
        sb.append(", addressType=").append(addressType);
        sb.append(", country=").append(country);
        sb.append(", postalCode=").append(postalCode);
        sb.append(", addressName=").append(addressName);
        sb.append(", contactor=").append(contactor);
        sb.append(", telephone=").append(telephone);
        sb.append(", pvStatus=").append(pvStatus);
        sb.append(", createdUserId=").append(createdUserId);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedUserId=").append(updatedUserId);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", deletedFlag=").append(deletedFlag);
        sb.append(", pvDesc=").append(pvDesc);
        sb.append("]");
        return sb.toString();
    }
}