package com.t.zero.yg.crm.bu.model.auto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class CorpInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.pv_code
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private String pvCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.tenant_id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.corp_brief
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private String corpBrief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.corp_name
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private String corpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.corp_type
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private String corpType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.industry_code
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private String industryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.pv_status
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private String pvStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.corp_level
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private Integer corpLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.corp_source
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private String corpSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.created_user_id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.created_time
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.updated_user_id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.updated_time
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private LocalDateTime updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.is_deleted
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private String deletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yg_corp_info.pv_desc
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private String pvDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.id
     *
     * @return the value of yg_corp_info.id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.id
     *
     * @param id the value for yg_corp_info.id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.pv_code
     *
     * @return the value of yg_corp_info.pv_code
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getPvCode() {
        return pvCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.pv_code
     *
     * @param pvCode the value for yg_corp_info.pv_code
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setPvCode(String pvCode) {
        this.pvCode = pvCode == null ? null : pvCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.tenant_id
     *
     * @return the value of yg_corp_info.tenant_id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.tenant_id
     *
     * @param tenantId the value for yg_corp_info.tenant_id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.corp_brief
     *
     * @return the value of yg_corp_info.corp_brief
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getCorpBrief() {
        return corpBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.corp_brief
     *
     * @param corpBrief the value for yg_corp_info.corp_brief
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setCorpBrief(String corpBrief) {
        this.corpBrief = corpBrief == null ? null : corpBrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.corp_name
     *
     * @return the value of yg_corp_info.corp_name
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.corp_name
     *
     * @param corpName the value for yg_corp_info.corp_name
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.corp_type
     *
     * @return the value of yg_corp_info.corp_type
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getCorpType() {
        return corpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.corp_type
     *
     * @param corpType the value for yg_corp_info.corp_type
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setCorpType(String corpType) {
        this.corpType = corpType == null ? null : corpType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.industry_code
     *
     * @return the value of yg_corp_info.industry_code
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.industry_code
     *
     * @param industryCode the value for yg_corp_info.industry_code
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setIndustryCode(String industryCode) {
        this.industryCode = industryCode == null ? null : industryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.pv_status
     *
     * @return the value of yg_corp_info.pv_status
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getPvStatus() {
        return pvStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.pv_status
     *
     * @param pvStatus the value for yg_corp_info.pv_status
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setPvStatus(String pvStatus) {
        this.pvStatus = pvStatus == null ? null : pvStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.corp_level
     *
     * @return the value of yg_corp_info.corp_level
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public Integer getCorpLevel() {
        return corpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.corp_level
     *
     * @param corpLevel the value for yg_corp_info.corp_level
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setCorpLevel(Integer corpLevel) {
        this.corpLevel = corpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.corp_source
     *
     * @return the value of yg_corp_info.corp_source
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getCorpSource() {
        return corpSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.corp_source
     *
     * @param corpSource the value for yg_corp_info.corp_source
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setCorpSource(String corpSource) {
        this.corpSource = corpSource == null ? null : corpSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.created_user_id
     *
     * @return the value of yg_corp_info.created_user_id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.created_user_id
     *
     * @param createdUserId the value for yg_corp_info.created_user_id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.created_time
     *
     * @return the value of yg_corp_info.created_time
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.created_time
     *
     * @param createdTime the value for yg_corp_info.created_time
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.updated_user_id
     *
     * @return the value of yg_corp_info.updated_user_id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.updated_user_id
     *
     * @param updatedUserId the value for yg_corp_info.updated_user_id
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId == null ? null : updatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.updated_time
     *
     * @return the value of yg_corp_info.updated_time
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.updated_time
     *
     * @param updatedTime the value for yg_corp_info.updated_time
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.is_deleted
     *
     * @return the value of yg_corp_info.is_deleted
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.is_deleted
     *
     * @param deletedFlag the value for yg_corp_info.is_deleted
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yg_corp_info.pv_desc
     *
     * @return the value of yg_corp_info.pv_desc
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public String getPvDesc() {
        return pvDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yg_corp_info.pv_desc
     *
     * @param pvDesc the value for yg_corp_info.pv_desc
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    public void setPvDesc(String pvDesc) {
        this.pvDesc = pvDesc == null ? null : pvDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yg_corp_info
     *
     * @mbg.generated Mon May 30 09:12:20 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pvCode=").append(pvCode);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", corpBrief=").append(corpBrief);
        sb.append(", corpName=").append(corpName);
        sb.append(", corpType=").append(corpType);
        sb.append(", industryCode=").append(industryCode);
        sb.append(", pvStatus=").append(pvStatus);
        sb.append(", corpLevel=").append(corpLevel);
        sb.append(", corpSource=").append(corpSource);
        sb.append(", createdUserId=").append(createdUserId);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedUserId=").append(updatedUserId);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", deletedFlag=").append(deletedFlag);
        sb.append(", pvDesc=").append(pvDesc);
        sb.append("]");
        return sb.toString();
    }
}