package com.t.zero.res.c.manager.bu.model.auto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class ResAuthRel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_auth_rel.id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_auth_rel.res_auth_id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    private Integer resAuthId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_auth_rel.res_auth_code
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    private String resAuthCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_auth_rel.res_auth_type
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    private String resAuthType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_auth_rel.res_auth_path
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    private String resAuthPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_auth_rel.res_info_id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    private Integer resInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_auth_rel.created_time
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_auth_rel.created_user_id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    private String createdUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_res_auth_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_auth_rel.id
     *
     * @return the value of t_zero_res_auth_rel.id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_auth_rel.id
     *
     * @param id the value for t_zero_res_auth_rel.id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_auth_rel.res_auth_id
     *
     * @return the value of t_zero_res_auth_rel.res_auth_id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public Integer getResAuthId() {
        return resAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_auth_rel.res_auth_id
     *
     * @param resAuthId the value for t_zero_res_auth_rel.res_auth_id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public void setResAuthId(Integer resAuthId) {
        this.resAuthId = resAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_auth_rel.res_auth_code
     *
     * @return the value of t_zero_res_auth_rel.res_auth_code
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public String getResAuthCode() {
        return resAuthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_auth_rel.res_auth_code
     *
     * @param resAuthCode the value for t_zero_res_auth_rel.res_auth_code
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public void setResAuthCode(String resAuthCode) {
        this.resAuthCode = resAuthCode == null ? null : resAuthCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_auth_rel.res_auth_type
     *
     * @return the value of t_zero_res_auth_rel.res_auth_type
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public String getResAuthType() {
        return resAuthType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_auth_rel.res_auth_type
     *
     * @param resAuthType the value for t_zero_res_auth_rel.res_auth_type
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public void setResAuthType(String resAuthType) {
        this.resAuthType = resAuthType == null ? null : resAuthType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_auth_rel.res_auth_path
     *
     * @return the value of t_zero_res_auth_rel.res_auth_path
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public String getResAuthPath() {
        return resAuthPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_auth_rel.res_auth_path
     *
     * @param resAuthPath the value for t_zero_res_auth_rel.res_auth_path
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public void setResAuthPath(String resAuthPath) {
        this.resAuthPath = resAuthPath == null ? null : resAuthPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_auth_rel.res_info_id
     *
     * @return the value of t_zero_res_auth_rel.res_info_id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public Integer getResInfoId() {
        return resInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_auth_rel.res_info_id
     *
     * @param resInfoId the value for t_zero_res_auth_rel.res_info_id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public void setResInfoId(Integer resInfoId) {
        this.resInfoId = resInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_auth_rel.created_time
     *
     * @return the value of t_zero_res_auth_rel.created_time
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_auth_rel.created_time
     *
     * @param createdTime the value for t_zero_res_auth_rel.created_time
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_auth_rel.created_user_id
     *
     * @return the value of t_zero_res_auth_rel.created_user_id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_auth_rel.created_user_id
     *
     * @param createdUserId the value for t_zero_res_auth_rel.created_user_id
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_auth_rel
     *
     * @mbg.generated Fri Feb 25 15:28:03 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", resAuthId=").append(resAuthId);
        sb.append(", resAuthCode=").append(resAuthCode);
        sb.append(", resAuthType=").append(resAuthType);
        sb.append(", resAuthPath=").append(resAuthPath);
        sb.append(", resInfoId=").append(resInfoId);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", createdUserId=").append(createdUserId);
        sb.append("]");
        return sb.toString();
    }
}