package com.t.zero.res.c.manager.bu.model.auto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class ResInfoDef implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.tenant_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.res_info_code
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String resInfoCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.res_info_name
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String resInfoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.res_info_type
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String resInfoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.res_content_type
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String resContentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.res_info_parent_code
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String resInfoParentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.res_info_store
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String resInfoStore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.res_info_size
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private Integer resInfoSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.version_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.res_info_desc
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String resInfoDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.res_info_owner_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private Integer resInfoOwnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.res_info_owner_type
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String resInfoOwnerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.created_time
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.created_user_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.updated_time
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private LocalDateTime updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.updated_user_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_res_info_def.is_deleted
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private String deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.id
     *
     * @return the value of t_zero_res_info_def.id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.id
     *
     * @param id the value for t_zero_res_info_def.id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.tenant_id
     *
     * @return the value of t_zero_res_info_def.tenant_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.tenant_id
     *
     * @param tenantId the value for t_zero_res_info_def.tenant_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.res_info_code
     *
     * @return the value of t_zero_res_info_def.res_info_code
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getResInfoCode() {
        return resInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.res_info_code
     *
     * @param resInfoCode the value for t_zero_res_info_def.res_info_code
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setResInfoCode(String resInfoCode) {
        this.resInfoCode = resInfoCode == null ? null : resInfoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.res_info_name
     *
     * @return the value of t_zero_res_info_def.res_info_name
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getResInfoName() {
        return resInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.res_info_name
     *
     * @param resInfoName the value for t_zero_res_info_def.res_info_name
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setResInfoName(String resInfoName) {
        this.resInfoName = resInfoName == null ? null : resInfoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.res_info_type
     *
     * @return the value of t_zero_res_info_def.res_info_type
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getResInfoType() {
        return resInfoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.res_info_type
     *
     * @param resInfoType the value for t_zero_res_info_def.res_info_type
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setResInfoType(String resInfoType) {
        this.resInfoType = resInfoType == null ? null : resInfoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.res_content_type
     *
     * @return the value of t_zero_res_info_def.res_content_type
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getResContentType() {
        return resContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.res_content_type
     *
     * @param resContentType the value for t_zero_res_info_def.res_content_type
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setResContentType(String resContentType) {
        this.resContentType = resContentType == null ? null : resContentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.res_info_parent_code
     *
     * @return the value of t_zero_res_info_def.res_info_parent_code
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getResInfoParentCode() {
        return resInfoParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.res_info_parent_code
     *
     * @param resInfoParentCode the value for t_zero_res_info_def.res_info_parent_code
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setResInfoParentCode(String resInfoParentCode) {
        this.resInfoParentCode = resInfoParentCode == null ? null : resInfoParentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.res_info_store
     *
     * @return the value of t_zero_res_info_def.res_info_store
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getResInfoStore() {
        return resInfoStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.res_info_store
     *
     * @param resInfoStore the value for t_zero_res_info_def.res_info_store
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setResInfoStore(String resInfoStore) {
        this.resInfoStore = resInfoStore == null ? null : resInfoStore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.res_info_size
     *
     * @return the value of t_zero_res_info_def.res_info_size
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public Integer getResInfoSize() {
        return resInfoSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.res_info_size
     *
     * @param resInfoSize the value for t_zero_res_info_def.res_info_size
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setResInfoSize(Integer resInfoSize) {
        this.resInfoSize = resInfoSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.version_id
     *
     * @return the value of t_zero_res_info_def.version_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.version_id
     *
     * @param versionId the value for t_zero_res_info_def.version_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.res_info_desc
     *
     * @return the value of t_zero_res_info_def.res_info_desc
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getResInfoDesc() {
        return resInfoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.res_info_desc
     *
     * @param resInfoDesc the value for t_zero_res_info_def.res_info_desc
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setResInfoDesc(String resInfoDesc) {
        this.resInfoDesc = resInfoDesc == null ? null : resInfoDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.res_info_owner_id
     *
     * @return the value of t_zero_res_info_def.res_info_owner_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public Integer getResInfoOwnerId() {
        return resInfoOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.res_info_owner_id
     *
     * @param resInfoOwnerId the value for t_zero_res_info_def.res_info_owner_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setResInfoOwnerId(Integer resInfoOwnerId) {
        this.resInfoOwnerId = resInfoOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.res_info_owner_type
     *
     * @return the value of t_zero_res_info_def.res_info_owner_type
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getResInfoOwnerType() {
        return resInfoOwnerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.res_info_owner_type
     *
     * @param resInfoOwnerType the value for t_zero_res_info_def.res_info_owner_type
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setResInfoOwnerType(String resInfoOwnerType) {
        this.resInfoOwnerType = resInfoOwnerType == null ? null : resInfoOwnerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.created_time
     *
     * @return the value of t_zero_res_info_def.created_time
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.created_time
     *
     * @param createdTime the value for t_zero_res_info_def.created_time
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.created_user_id
     *
     * @return the value of t_zero_res_info_def.created_user_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.created_user_id
     *
     * @param createdUserId the value for t_zero_res_info_def.created_user_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.updated_time
     *
     * @return the value of t_zero_res_info_def.updated_time
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.updated_time
     *
     * @param updatedTime the value for t_zero_res_info_def.updated_time
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.updated_user_id
     *
     * @return the value of t_zero_res_info_def.updated_user_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.updated_user_id
     *
     * @param updatedUserId the value for t_zero_res_info_def.updated_user_id
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId == null ? null : updatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_res_info_def.is_deleted
     *
     * @return the value of t_zero_res_info_def.is_deleted
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_res_info_def.is_deleted
     *
     * @param deletedFlag the value for t_zero_res_info_def.is_deleted
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_info_def
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", resInfoCode=").append(resInfoCode);
        sb.append(", resInfoName=").append(resInfoName);
        sb.append(", resInfoType=").append(resInfoType);
        sb.append(", resContentType=").append(resContentType);
        sb.append(", resInfoParentCode=").append(resInfoParentCode);
        sb.append(", resInfoStore=").append(resInfoStore);
        sb.append(", resInfoSize=").append(resInfoSize);
        sb.append(", versionId=").append(versionId);
        sb.append(", resInfoDesc=").append(resInfoDesc);
        sb.append(", resInfoOwnerId=").append(resInfoOwnerId);
        sb.append(", resInfoOwnerType=").append(resInfoOwnerType);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", createdUserId=").append(createdUserId);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", updatedUserId=").append(updatedUserId);
        sb.append(", deletedFlag=").append(deletedFlag);
        sb.append("]");
        return sb.toString();
    }
}