package com.t.zero.res.c.manager.bu.model.auto;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class ResTagRelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public ResTagRelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andResTagIdIsNull() {
            addCriterion("res_tag_id is null");
            return (Criteria) this;
        }

        public Criteria andResTagIdIsNotNull() {
            addCriterion("res_tag_id is not null");
            return (Criteria) this;
        }

        public Criteria andResTagIdEqualTo(Integer value) {
            addCriterion("res_tag_id =", value, "resTagId");
            return (Criteria) this;
        }

        public Criteria andResTagIdNotEqualTo(Integer value) {
            addCriterion("res_tag_id <>", value, "resTagId");
            return (Criteria) this;
        }

        public Criteria andResTagIdGreaterThan(Integer value) {
            addCriterion("res_tag_id >", value, "resTagId");
            return (Criteria) this;
        }

        public Criteria andResTagIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("res_tag_id >=", value, "resTagId");
            return (Criteria) this;
        }

        public Criteria andResTagIdLessThan(Integer value) {
            addCriterion("res_tag_id <", value, "resTagId");
            return (Criteria) this;
        }

        public Criteria andResTagIdLessThanOrEqualTo(Integer value) {
            addCriterion("res_tag_id <=", value, "resTagId");
            return (Criteria) this;
        }

        public Criteria andResTagIdIn(List<Integer> values) {
            addCriterion("res_tag_id in", values, "resTagId");
            return (Criteria) this;
        }

        public Criteria andResTagIdNotIn(List<Integer> values) {
            addCriterion("res_tag_id not in", values, "resTagId");
            return (Criteria) this;
        }

        public Criteria andResTagIdBetween(Integer value1, Integer value2) {
            addCriterion("res_tag_id between", value1, value2, "resTagId");
            return (Criteria) this;
        }

        public Criteria andResTagIdNotBetween(Integer value1, Integer value2) {
            addCriterion("res_tag_id not between", value1, value2, "resTagId");
            return (Criteria) this;
        }

        public Criteria andResTagCodeIsNull() {
            addCriterion("res_tag_code is null");
            return (Criteria) this;
        }

        public Criteria andResTagCodeIsNotNull() {
            addCriterion("res_tag_code is not null");
            return (Criteria) this;
        }

        public Criteria andResTagCodeEqualTo(String value) {
            addCriterion("res_tag_code =", value, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResTagCodeNotEqualTo(String value) {
            addCriterion("res_tag_code <>", value, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResTagCodeGreaterThan(String value) {
            addCriterion("res_tag_code >", value, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResTagCodeGreaterThanOrEqualTo(String value) {
            addCriterion("res_tag_code >=", value, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResTagCodeLessThan(String value) {
            addCriterion("res_tag_code <", value, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResTagCodeLessThanOrEqualTo(String value) {
            addCriterion("res_tag_code <=", value, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResTagCodeLike(String value) {
            addCriterion("res_tag_code like", value, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResTagCodeNotLike(String value) {
            addCriterion("res_tag_code not like", value, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResTagCodeIn(List<String> values) {
            addCriterion("res_tag_code in", values, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResTagCodeNotIn(List<String> values) {
            addCriterion("res_tag_code not in", values, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResTagCodeBetween(String value1, String value2) {
            addCriterion("res_tag_code between", value1, value2, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResTagCodeNotBetween(String value1, String value2) {
            addCriterion("res_tag_code not between", value1, value2, "resTagCode");
            return (Criteria) this;
        }

        public Criteria andResInfoIdIsNull() {
            addCriterion("res_info_id is null");
            return (Criteria) this;
        }

        public Criteria andResInfoIdIsNotNull() {
            addCriterion("res_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andResInfoIdEqualTo(Integer value) {
            addCriterion("res_info_id =", value, "resInfoId");
            return (Criteria) this;
        }

        public Criteria andResInfoIdNotEqualTo(Integer value) {
            addCriterion("res_info_id <>", value, "resInfoId");
            return (Criteria) this;
        }

        public Criteria andResInfoIdGreaterThan(Integer value) {
            addCriterion("res_info_id >", value, "resInfoId");
            return (Criteria) this;
        }

        public Criteria andResInfoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("res_info_id >=", value, "resInfoId");
            return (Criteria) this;
        }

        public Criteria andResInfoIdLessThan(Integer value) {
            addCriterion("res_info_id <", value, "resInfoId");
            return (Criteria) this;
        }

        public Criteria andResInfoIdLessThanOrEqualTo(Integer value) {
            addCriterion("res_info_id <=", value, "resInfoId");
            return (Criteria) this;
        }

        public Criteria andResInfoIdIn(List<Integer> values) {
            addCriterion("res_info_id in", values, "resInfoId");
            return (Criteria) this;
        }

        public Criteria andResInfoIdNotIn(List<Integer> values) {
            addCriterion("res_info_id not in", values, "resInfoId");
            return (Criteria) this;
        }

        public Criteria andResInfoIdBetween(Integer value1, Integer value2) {
            addCriterion("res_info_id between", value1, value2, "resInfoId");
            return (Criteria) this;
        }

        public Criteria andResInfoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("res_info_id not between", value1, value2, "resInfoId");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeIsNull() {
            addCriterion("res_info_code is null");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeIsNotNull() {
            addCriterion("res_info_code is not null");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeEqualTo(String value) {
            addCriterion("res_info_code =", value, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeNotEqualTo(String value) {
            addCriterion("res_info_code <>", value, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeGreaterThan(String value) {
            addCriterion("res_info_code >", value, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeGreaterThanOrEqualTo(String value) {
            addCriterion("res_info_code >=", value, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeLessThan(String value) {
            addCriterion("res_info_code <", value, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeLessThanOrEqualTo(String value) {
            addCriterion("res_info_code <=", value, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeLike(String value) {
            addCriterion("res_info_code like", value, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeNotLike(String value) {
            addCriterion("res_info_code not like", value, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeIn(List<String> values) {
            addCriterion("res_info_code in", values, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeNotIn(List<String> values) {
            addCriterion("res_info_code not in", values, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeBetween(String value1, String value2) {
            addCriterion("res_info_code between", value1, value2, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andResInfoCodeNotBetween(String value1, String value2) {
            addCriterion("res_info_code not between", value1, value2, "resInfoCode");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(LocalDateTime value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(LocalDateTime value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(LocalDateTime value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(LocalDateTime value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<LocalDateTime> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<LocalDateTime> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIsNull() {
            addCriterion("created_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIsNotNull() {
            addCriterion("created_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdEqualTo(String value) {
            addCriterion("created_user_id =", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotEqualTo(String value) {
            addCriterion("created_user_id <>", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdGreaterThan(String value) {
            addCriterion("created_user_id >", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("created_user_id >=", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLessThan(String value) {
            addCriterion("created_user_id <", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLessThanOrEqualTo(String value) {
            addCriterion("created_user_id <=", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLike(String value) {
            addCriterion("created_user_id like", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotLike(String value) {
            addCriterion("created_user_id not like", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIn(List<String> values) {
            addCriterion("created_user_id in", values, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotIn(List<String> values) {
            addCriterion("created_user_id not in", values, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdBetween(String value1, String value2) {
            addCriterion("created_user_id between", value1, value2, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotBetween(String value1, String value2) {
            addCriterion("created_user_id not between", value1, value2, "createdUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated do_not_delete_during_merge Tue May 17 13:12:23 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_zero_res_tag_rel
     *
     * @mbg.generated Tue May 17 13:12:23 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}