package com.t.zero.res.c.manager.bu.model.auto;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TemplateInfoDefExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    public TemplateInfoDefExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdIsNull() {
            addCriterion("template_type_id is null");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdIsNotNull() {
            addCriterion("template_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdEqualTo(Integer value) {
            addCriterion("template_type_id =", value, "templateTypeId");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdNotEqualTo(Integer value) {
            addCriterion("template_type_id <>", value, "templateTypeId");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdGreaterThan(Integer value) {
            addCriterion("template_type_id >", value, "templateTypeId");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("template_type_id >=", value, "templateTypeId");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdLessThan(Integer value) {
            addCriterion("template_type_id <", value, "templateTypeId");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("template_type_id <=", value, "templateTypeId");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdIn(List<Integer> values) {
            addCriterion("template_type_id in", values, "templateTypeId");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdNotIn(List<Integer> values) {
            addCriterion("template_type_id not in", values, "templateTypeId");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("template_type_id between", value1, value2, "templateTypeId");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("template_type_id not between", value1, value2, "templateTypeId");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeIsNull() {
            addCriterion("template_type_code is null");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeIsNotNull() {
            addCriterion("template_type_code is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeEqualTo(String value) {
            addCriterion("template_type_code =", value, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeNotEqualTo(String value) {
            addCriterion("template_type_code <>", value, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeGreaterThan(String value) {
            addCriterion("template_type_code >", value, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("template_type_code >=", value, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeLessThan(String value) {
            addCriterion("template_type_code <", value, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("template_type_code <=", value, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeLike(String value) {
            addCriterion("template_type_code like", value, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeNotLike(String value) {
            addCriterion("template_type_code not like", value, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeIn(List<String> values) {
            addCriterion("template_type_code in", values, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeNotIn(List<String> values) {
            addCriterion("template_type_code not in", values, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeBetween(String value1, String value2) {
            addCriterion("template_type_code between", value1, value2, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeCodeNotBetween(String value1, String value2) {
            addCriterion("template_type_code not between", value1, value2, "templateTypeCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeIsNull() {
            addCriterion("template_info_code is null");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeIsNotNull() {
            addCriterion("template_info_code is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeEqualTo(String value) {
            addCriterion("template_info_code =", value, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeNotEqualTo(String value) {
            addCriterion("template_info_code <>", value, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeGreaterThan(String value) {
            addCriterion("template_info_code >", value, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeGreaterThanOrEqualTo(String value) {
            addCriterion("template_info_code >=", value, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeLessThan(String value) {
            addCriterion("template_info_code <", value, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeLessThanOrEqualTo(String value) {
            addCriterion("template_info_code <=", value, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeLike(String value) {
            addCriterion("template_info_code like", value, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeNotLike(String value) {
            addCriterion("template_info_code not like", value, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeIn(List<String> values) {
            addCriterion("template_info_code in", values, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeNotIn(List<String> values) {
            addCriterion("template_info_code not in", values, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeBetween(String value1, String value2) {
            addCriterion("template_info_code between", value1, value2, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoCodeNotBetween(String value1, String value2) {
            addCriterion("template_info_code not between", value1, value2, "templateInfoCode");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameIsNull() {
            addCriterion("template_info_name is null");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameIsNotNull() {
            addCriterion("template_info_name is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameEqualTo(String value) {
            addCriterion("template_info_name =", value, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameNotEqualTo(String value) {
            addCriterion("template_info_name <>", value, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameGreaterThan(String value) {
            addCriterion("template_info_name >", value, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameGreaterThanOrEqualTo(String value) {
            addCriterion("template_info_name >=", value, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameLessThan(String value) {
            addCriterion("template_info_name <", value, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameLessThanOrEqualTo(String value) {
            addCriterion("template_info_name <=", value, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameLike(String value) {
            addCriterion("template_info_name like", value, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameNotLike(String value) {
            addCriterion("template_info_name not like", value, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameIn(List<String> values) {
            addCriterion("template_info_name in", values, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameNotIn(List<String> values) {
            addCriterion("template_info_name not in", values, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameBetween(String value1, String value2) {
            addCriterion("template_info_name between", value1, value2, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateInfoNameNotBetween(String value1, String value2) {
            addCriterion("template_info_name not between", value1, value2, "templateInfoName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameIsNull() {
            addCriterion("template_file_name is null");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameIsNotNull() {
            addCriterion("template_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameEqualTo(String value) {
            addCriterion("template_file_name =", value, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameNotEqualTo(String value) {
            addCriterion("template_file_name <>", value, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameGreaterThan(String value) {
            addCriterion("template_file_name >", value, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("template_file_name >=", value, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameLessThan(String value) {
            addCriterion("template_file_name <", value, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameLessThanOrEqualTo(String value) {
            addCriterion("template_file_name <=", value, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameLike(String value) {
            addCriterion("template_file_name like", value, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameNotLike(String value) {
            addCriterion("template_file_name not like", value, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameIn(List<String> values) {
            addCriterion("template_file_name in", values, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameNotIn(List<String> values) {
            addCriterion("template_file_name not in", values, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameBetween(String value1, String value2) {
            addCriterion("template_file_name between", value1, value2, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNameNotBetween(String value1, String value2) {
            addCriterion("template_file_name not between", value1, value2, "templateFileName");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressIsNull() {
            addCriterion("template_file_address is null");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressIsNotNull() {
            addCriterion("template_file_address is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressEqualTo(String value) {
            addCriterion("template_file_address =", value, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressNotEqualTo(String value) {
            addCriterion("template_file_address <>", value, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressGreaterThan(String value) {
            addCriterion("template_file_address >", value, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressGreaterThanOrEqualTo(String value) {
            addCriterion("template_file_address >=", value, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressLessThan(String value) {
            addCriterion("template_file_address <", value, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressLessThanOrEqualTo(String value) {
            addCriterion("template_file_address <=", value, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressLike(String value) {
            addCriterion("template_file_address like", value, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressNotLike(String value) {
            addCriterion("template_file_address not like", value, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressIn(List<String> values) {
            addCriterion("template_file_address in", values, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressNotIn(List<String> values) {
            addCriterion("template_file_address not in", values, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressBetween(String value1, String value2) {
            addCriterion("template_file_address between", value1, value2, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileAddressNotBetween(String value1, String value2) {
            addCriterion("template_file_address not between", value1, value2, "templateFileAddress");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageIsNull() {
            addCriterion("template_file_storage is null");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageIsNotNull() {
            addCriterion("template_file_storage is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageEqualTo(String value) {
            addCriterion("template_file_storage =", value, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageNotEqualTo(String value) {
            addCriterion("template_file_storage <>", value, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageGreaterThan(String value) {
            addCriterion("template_file_storage >", value, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageGreaterThanOrEqualTo(String value) {
            addCriterion("template_file_storage >=", value, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageLessThan(String value) {
            addCriterion("template_file_storage <", value, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageLessThanOrEqualTo(String value) {
            addCriterion("template_file_storage <=", value, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageLike(String value) {
            addCriterion("template_file_storage like", value, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageNotLike(String value) {
            addCriterion("template_file_storage not like", value, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageIn(List<String> values) {
            addCriterion("template_file_storage in", values, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageNotIn(List<String> values) {
            addCriterion("template_file_storage not in", values, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageBetween(String value1, String value2) {
            addCriterion("template_file_storage between", value1, value2, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andTemplateFileStorageNotBetween(String value1, String value2) {
            addCriterion("template_file_storage not between", value1, value2, "templateFileStorage");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIsNull() {
            addCriterion("created_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIsNotNull() {
            addCriterion("created_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdEqualTo(String value) {
            addCriterion("created_user_id =", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotEqualTo(String value) {
            addCriterion("created_user_id <>", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdGreaterThan(String value) {
            addCriterion("created_user_id >", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("created_user_id >=", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLessThan(String value) {
            addCriterion("created_user_id <", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLessThanOrEqualTo(String value) {
            addCriterion("created_user_id <=", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLike(String value) {
            addCriterion("created_user_id like", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotLike(String value) {
            addCriterion("created_user_id not like", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIn(List<String> values) {
            addCriterion("created_user_id in", values, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotIn(List<String> values) {
            addCriterion("created_user_id not in", values, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdBetween(String value1, String value2) {
            addCriterion("created_user_id between", value1, value2, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotBetween(String value1, String value2) {
            addCriterion("created_user_id not between", value1, value2, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(LocalDateTime value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(LocalDateTime value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(LocalDateTime value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(LocalDateTime value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<LocalDateTime> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<LocalDateTime> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdIsNull() {
            addCriterion("updated_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdIsNotNull() {
            addCriterion("updated_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdEqualTo(String value) {
            addCriterion("updated_user_id =", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotEqualTo(String value) {
            addCriterion("updated_user_id <>", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdGreaterThan(String value) {
            addCriterion("updated_user_id >", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("updated_user_id >=", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdLessThan(String value) {
            addCriterion("updated_user_id <", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdLessThanOrEqualTo(String value) {
            addCriterion("updated_user_id <=", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdLike(String value) {
            addCriterion("updated_user_id like", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotLike(String value) {
            addCriterion("updated_user_id not like", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdIn(List<String> values) {
            addCriterion("updated_user_id in", values, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotIn(List<String> values) {
            addCriterion("updated_user_id not in", values, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdBetween(String value1, String value2) {
            addCriterion("updated_user_id between", value1, value2, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotBetween(String value1, String value2) {
            addCriterion("updated_user_id not between", value1, value2, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(LocalDateTime value) {
            addCriterion("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(LocalDateTime value) {
            addCriterion("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(LocalDateTime value) {
            addCriterion("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(LocalDateTime value) {
            addCriterion("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<LocalDateTime> values) {
            addCriterion("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<LocalDateTime> values) {
            addCriterion("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagEqualTo(String value) {
            addCriterion("is_deleted =", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThan(String value) {
            addCriterion("is_deleted >", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThan(String value) {
            addCriterion("is_deleted <", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLike(String value) {
            addCriterion("is_deleted like", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotLike(String value) {
            addCriterion("is_deleted not like", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIn(List<String> values) {
            addCriterion("is_deleted in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated do_not_delete_during_merge Tue May 17 13:12:24 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_zero_template_info_def
     *
     * @mbg.generated Tue May 17 13:12:24 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}