package com.t.zero.cust.app.bu.dao.auto;

import com.t.zero.cust.app.bu.model.auto.CustRelTagApp;
import com.t.zero.cust.app.bu.model.auto.CustRelTagAppExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustRelTagAppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    long countByExample(CustRelTagAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int deleteByExample(CustRelTagAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int insert(CustRelTagApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int insertSelective(CustRelTagApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    List<CustRelTagApp> selectByExample(CustRelTagAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    CustRelTagApp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByExampleSelective(@Param("record") CustRelTagApp record, @Param("example") CustRelTagAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByExample(@Param("record") CustRelTagApp record, @Param("example") CustRelTagAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByPrimaryKeySelective(CustRelTagApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByPrimaryKey(CustRelTagApp record);
}