package com.t.zero.cust.app.bu.dao.auto;

import com.t.zero.cust.app.bu.model.auto.CustRelTagGroup;
import com.t.zero.cust.app.bu.model.auto.CustRelTagGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustRelTagGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    long countByExample(CustRelTagGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int deleteByExample(CustRelTagGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int insert(CustRelTagGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int insertSelective(CustRelTagGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    List<CustRelTagGroup> selectByExample(CustRelTagGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    CustRelTagGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByExampleSelective(@Param("record") CustRelTagGroup record, @Param("example") CustRelTagGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByExample(@Param("record") CustRelTagGroup record, @Param("example") CustRelTagGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByPrimaryKeySelective(CustRelTagGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByPrimaryKey(CustRelTagGroup record);
}