package com.t.zero.cust.app.bu.dao.auto;

import com.t.zero.cust.app.bu.model.auto.CustAppInfo;
import com.t.zero.cust.app.bu.model.auto.CustAppInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustAppInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    long countByExample(CustAppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int deleteByExample(CustAppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int insert(CustAppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int insertSelective(CustAppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    List<CustAppInfo> selectByExampleWithBLOBs(CustAppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    List<CustAppInfo> selectByExample(CustAppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    CustAppInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByExampleSelective(@Param("record") CustAppInfo record, @Param("example") CustAppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CustAppInfo record, @Param("example") CustAppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByExample(@Param("record") CustAppInfo record, @Param("example") CustAppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByPrimaryKeySelective(CustAppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CustAppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByPrimaryKey(CustAppInfo record);
}