package com.t.zero.cust.app.bu.dao.auto;

import com.t.zero.cust.app.bu.model.auto.CustTagGroup;
import com.t.zero.cust.app.bu.model.auto.CustTagGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustTagGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    long countByExample(CustTagGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int deleteByExample(CustTagGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int insert(CustTagGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int insertSelective(CustTagGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    List<CustTagGroup> selectByExample(CustTagGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    CustTagGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByExampleSelective(@Param("record") CustTagGroup record, @Param("example") CustTagGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByExample(@Param("record") CustTagGroup record, @Param("example") CustTagGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByPrimaryKeySelective(CustTagGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    int updateByPrimaryKey(CustTagGroup record);
}