package com.t.zero.cust.app.bu.model.auto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class CustTagGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_tag_group.id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_tag_group.tenant_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_tag_group.tag_group_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String tagGroupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_tag_group.tag_group_name
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String tagGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_tag_group.created_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_tag_group.created_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_tag_group.updated_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_tag_group.updated_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private LocalDateTime updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_tag_group.is_deleted
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_tag_group.id
     *
     * @return the value of t_zero_cust_tag_group.id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_tag_group.id
     *
     * @param id the value for t_zero_cust_tag_group.id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_tag_group.tenant_id
     *
     * @return the value of t_zero_cust_tag_group.tenant_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_tag_group.tenant_id
     *
     * @param tenantId the value for t_zero_cust_tag_group.tenant_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_tag_group.tag_group_code
     *
     * @return the value of t_zero_cust_tag_group.tag_group_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getTagGroupCode() {
        return tagGroupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_tag_group.tag_group_code
     *
     * @param tagGroupCode the value for t_zero_cust_tag_group.tag_group_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setTagGroupCode(String tagGroupCode) {
        this.tagGroupCode = tagGroupCode == null ? null : tagGroupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_tag_group.tag_group_name
     *
     * @return the value of t_zero_cust_tag_group.tag_group_name
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getTagGroupName() {
        return tagGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_tag_group.tag_group_name
     *
     * @param tagGroupName the value for t_zero_cust_tag_group.tag_group_name
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setTagGroupName(String tagGroupName) {
        this.tagGroupName = tagGroupName == null ? null : tagGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_tag_group.created_user_id
     *
     * @return the value of t_zero_cust_tag_group.created_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_tag_group.created_user_id
     *
     * @param createdUserId the value for t_zero_cust_tag_group.created_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_tag_group.created_time
     *
     * @return the value of t_zero_cust_tag_group.created_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_tag_group.created_time
     *
     * @param createdTime the value for t_zero_cust_tag_group.created_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_tag_group.updated_user_id
     *
     * @return the value of t_zero_cust_tag_group.updated_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_tag_group.updated_user_id
     *
     * @param updatedUserId the value for t_zero_cust_tag_group.updated_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId == null ? null : updatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_tag_group.updated_time
     *
     * @return the value of t_zero_cust_tag_group.updated_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_tag_group.updated_time
     *
     * @param updatedTime the value for t_zero_cust_tag_group.updated_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_tag_group.is_deleted
     *
     * @return the value of t_zero_cust_tag_group.is_deleted
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_tag_group.is_deleted
     *
     * @param deletedFlag the value for t_zero_cust_tag_group.is_deleted
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_tag_group
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", tagGroupCode=").append(tagGroupCode);
        sb.append(", tagGroupName=").append(tagGroupName);
        sb.append(", createdUserId=").append(createdUserId);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedUserId=").append(updatedUserId);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", deletedFlag=").append(deletedFlag);
        sb.append("]");
        return sb.toString();
    }
}