package com.t.zero.cust.app.bu.model.auto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class CustAppInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.tenant_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.app_info_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String appInfoCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.app_info_name
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String appInfoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.app_info_logo
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String appInfoLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.app_info_type
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String appInfoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.app_info_link
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String appInfoLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.owner_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.created_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.created_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.updated_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.updated_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private LocalDateTime updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.is_deleted
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String deletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_app_info.app_info_attrs
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String appInfoAttrs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.id
     *
     * @return the value of t_zero_cust_app_info.id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.id
     *
     * @param id the value for t_zero_cust_app_info.id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.tenant_id
     *
     * @return the value of t_zero_cust_app_info.tenant_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.tenant_id
     *
     * @param tenantId the value for t_zero_cust_app_info.tenant_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.app_info_code
     *
     * @return the value of t_zero_cust_app_info.app_info_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getAppInfoCode() {
        return appInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.app_info_code
     *
     * @param appInfoCode the value for t_zero_cust_app_info.app_info_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setAppInfoCode(String appInfoCode) {
        this.appInfoCode = appInfoCode == null ? null : appInfoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.app_info_name
     *
     * @return the value of t_zero_cust_app_info.app_info_name
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getAppInfoName() {
        return appInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.app_info_name
     *
     * @param appInfoName the value for t_zero_cust_app_info.app_info_name
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setAppInfoName(String appInfoName) {
        this.appInfoName = appInfoName == null ? null : appInfoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.app_info_logo
     *
     * @return the value of t_zero_cust_app_info.app_info_logo
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getAppInfoLogo() {
        return appInfoLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.app_info_logo
     *
     * @param appInfoLogo the value for t_zero_cust_app_info.app_info_logo
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setAppInfoLogo(String appInfoLogo) {
        this.appInfoLogo = appInfoLogo == null ? null : appInfoLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.app_info_type
     *
     * @return the value of t_zero_cust_app_info.app_info_type
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getAppInfoType() {
        return appInfoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.app_info_type
     *
     * @param appInfoType the value for t_zero_cust_app_info.app_info_type
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setAppInfoType(String appInfoType) {
        this.appInfoType = appInfoType == null ? null : appInfoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.app_info_link
     *
     * @return the value of t_zero_cust_app_info.app_info_link
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getAppInfoLink() {
        return appInfoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.app_info_link
     *
     * @param appInfoLink the value for t_zero_cust_app_info.app_info_link
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setAppInfoLink(String appInfoLink) {
        this.appInfoLink = appInfoLink == null ? null : appInfoLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.owner_id
     *
     * @return the value of t_zero_cust_app_info.owner_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.owner_id
     *
     * @param ownerId the value for t_zero_cust_app_info.owner_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.created_user_id
     *
     * @return the value of t_zero_cust_app_info.created_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.created_user_id
     *
     * @param createdUserId the value for t_zero_cust_app_info.created_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.created_time
     *
     * @return the value of t_zero_cust_app_info.created_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.created_time
     *
     * @param createdTime the value for t_zero_cust_app_info.created_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.updated_user_id
     *
     * @return the value of t_zero_cust_app_info.updated_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.updated_user_id
     *
     * @param updatedUserId the value for t_zero_cust_app_info.updated_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId == null ? null : updatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.updated_time
     *
     * @return the value of t_zero_cust_app_info.updated_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.updated_time
     *
     * @param updatedTime the value for t_zero_cust_app_info.updated_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.is_deleted
     *
     * @return the value of t_zero_cust_app_info.is_deleted
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.is_deleted
     *
     * @param deletedFlag the value for t_zero_cust_app_info.is_deleted
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_app_info.app_info_attrs
     *
     * @return the value of t_zero_cust_app_info.app_info_attrs
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getAppInfoAttrs() {
        return appInfoAttrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_app_info.app_info_attrs
     *
     * @param appInfoAttrs the value for t_zero_cust_app_info.app_info_attrs
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setAppInfoAttrs(String appInfoAttrs) {
        this.appInfoAttrs = appInfoAttrs == null ? null : appInfoAttrs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_app_info
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", appInfoCode=").append(appInfoCode);
        sb.append(", appInfoName=").append(appInfoName);
        sb.append(", appInfoLogo=").append(appInfoLogo);
        sb.append(", appInfoType=").append(appInfoType);
        sb.append(", appInfoLink=").append(appInfoLink);
        sb.append(", ownerId=").append(ownerId);
        sb.append(", createdUserId=").append(createdUserId);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedUserId=").append(updatedUserId);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", deletedFlag=").append(deletedFlag);
        sb.append(", appInfoAttrs=").append(appInfoAttrs);
        sb.append("]");
        return sb.toString();
    }
}