package com.t.zero.cust.app.bu.model.auto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class CustRelTagApp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_rel_tag_app.id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_rel_tag_app.tag_info_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String tagInfoCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_rel_tag_app.tag_info_name
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String tagInfoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_rel_tag_app.ap_info_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String apInfoCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_rel_tag_app.created_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_cust_rel_tag_app.created_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private LocalDateTime createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_rel_tag_app.id
     *
     * @return the value of t_zero_cust_rel_tag_app.id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_rel_tag_app.id
     *
     * @param id the value for t_zero_cust_rel_tag_app.id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_rel_tag_app.tag_info_code
     *
     * @return the value of t_zero_cust_rel_tag_app.tag_info_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getTagInfoCode() {
        return tagInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_rel_tag_app.tag_info_code
     *
     * @param tagInfoCode the value for t_zero_cust_rel_tag_app.tag_info_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setTagInfoCode(String tagInfoCode) {
        this.tagInfoCode = tagInfoCode == null ? null : tagInfoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_rel_tag_app.tag_info_name
     *
     * @return the value of t_zero_cust_rel_tag_app.tag_info_name
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getTagInfoName() {
        return tagInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_rel_tag_app.tag_info_name
     *
     * @param tagInfoName the value for t_zero_cust_rel_tag_app.tag_info_name
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setTagInfoName(String tagInfoName) {
        this.tagInfoName = tagInfoName == null ? null : tagInfoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_rel_tag_app.ap_info_code
     *
     * @return the value of t_zero_cust_rel_tag_app.ap_info_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getApInfoCode() {
        return apInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_rel_tag_app.ap_info_code
     *
     * @param apInfoCode the value for t_zero_cust_rel_tag_app.ap_info_code
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setApInfoCode(String apInfoCode) {
        this.apInfoCode = apInfoCode == null ? null : apInfoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_rel_tag_app.created_user_id
     *
     * @return the value of t_zero_cust_rel_tag_app.created_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_rel_tag_app.created_user_id
     *
     * @param createdUserId the value for t_zero_cust_rel_tag_app.created_user_id
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_cust_rel_tag_app.created_time
     *
     * @return the value of t_zero_cust_rel_tag_app.created_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_cust_rel_tag_app.created_time
     *
     * @param createdTime the value for t_zero_cust_rel_tag_app.created_time
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_cust_rel_tag_app
     *
     * @mbg.generated Tue Apr 12 10:26:08 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tagInfoCode=").append(tagInfoCode);
        sb.append(", tagInfoName=").append(tagInfoName);
        sb.append(", apInfoCode=").append(apInfoCode);
        sb.append(", createdUserId=").append(createdUserId);
        sb.append(", createdTime=").append(createdTime);
        sb.append("]");
        return sb.toString();
    }
}