spring:
   datasource:
      name: dataSource
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://47.111.15.144:3306/yg_crm?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
      username: u_yg_crm
      password: tZeroDavin!123
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
         connection-test-query: select now()
         idle-timeout: 3000000
         auto-commit: true
         max-lifetime: 1200000
         maximum-pool-size: 60
         minimum-idle: 10
         login-timeout: 5
         validation-timeout: 300000
         connection-timeout: 600000000
         read-only: false
mybatis:
   configuration:
      ocal-cache-scope: statement
   mapper-locations:
   - auto-mappers/*.xml
   - manual-mappers/*.xml